# Generated by Django 3.2.4 on 2021-08-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporthangout', '0002_locationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationinfo',
            name='lat',
            field=models.CharField(default=False, max_length=120),
        ),
        migrations.AddField(
            model_name='locationinfo',
            name='lot',
            field=models.CharField(default=False, max_length=120),
        ),
    ]
